<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ed_migrate"
 *
 * Auto generated by Extension Builder 2015-11-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array (
	'title' => 'Essential Dots Migrate Library',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Nikola Stojiljkovic',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.5',
	'constraints' => 
	array (
	  'depends' => 
	  array (
	    'typo3' => '7.0.0-0.0.0',
	  ),
	  'conflicts' => 
	  array (
	  ),
	  'suggests' => 
	  array (
	  ),
	),
);

?>